### ISSUE TITLE
Hi, how to run it?

### ISSUE THREAD

**Issue by thecsw** [jarhill0/JavaGameSandbox#1]
Hi, just was wondering, how to run it?
Can't find main class. Thanks.

**Comment by jarhill0** [comment]
`Game.java` is the main class. I use IntelliJ IDEA to run it, and I don't know beyond that how to get it to run.

The code is a mess and it's really just for me to play around with, but if you get it working, let me know!

Controls are WASD/arrows and IJKL.

**Comment by thecsw** [comment]
Well, thanks for the fastest issue response in my life. I will try to run it tomorrow on my eclipse, if not then IntelliJI. 
**Happy New Year!**

**Comment by jarhill0** [comment]
Thanks, Happy New Year to you too!

**Comment by jarhill0** [comment]
Hey — not sure if you're still interested @thecsw, but I figured out how to compile it to a `.jar` file and I put that up on the [releases page](https://github.com/jarhill0/JavaGameSandbox/releases/tag/v0.1).
