### ISSUE TITLE
Hey! 

### ISSUE THREAD

**Issue by thecsw** [jarhill0/JavaGameSandbox#2]
Hello there! How are you? Hope you're doing good!
I don't know other ways of communications,  so I'm opening an issue.

I wanted to tell you about the new project I have been doing with another guy. It is a Reddit bot that is working in the r/PewdiepieSubmissions. I don't know if you watch Felix or not, he has his LWAIY (copy of YAIY) series where he reviews the most upvoted submissions. A lot of the posted jokes are stale and not funny. So I created a bot that used PRAW and textrecog to find stale memes and warn users. 

If you have some free time, you can check it out here -> https://github.com/thecsw/MemePolice_bot

Here is the link to the bot -> https://www.reddit.com/user/MemePolice_bot/

You can just ignore it if you are not interested, no problem!

Have a nice day!

_Sincerely, 
thecsw_

**Comment by thecsw** [comment]
btw, you helped me on my Collatz Conjecture bot -> https://github.com/thecsw/collatz

**Comment by jarhill0** [comment]
Cool stuff! Nice work on the image recognition and processing.
